FROM python:alpine

MAINTAINER songmengyun songmengyun@jmuer.com

# 添加标签说明
LABEL purpose="Auto testing for Poseidon"

# 设置用户
USER root

# 设置时区变量
ENV TIME_ZONE Asia/Shanghai

# 设置 apk源、 pip源并安装pycurl和mysqlclient
RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.9/main/" > /etc/apk/repositories \
    && apk add --no-cache -U tzdata \
    && ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime \
    && echo "${TIME_ZONE}" > /etc/timezone \

COPY pip.conf /root/.pip/

RUN mkdir  /root/.pip/ \
    && apk add build-base \
    && apk add curl \
    && apk add curl-dev \
    && pip install pycurl \
    && apk add mariadb-connector-c-dev \
    && pip install mysqlclient

# 根据requirements安装python第三方库
COPY requirements.txt /root/
RUN pip install -r /root/requirements.txt
